spring:
  application:
    name: backend
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
<<<<<<< HEAD
        'format_sql': true
        'show_sql': true
=======
        '[format_sql]': true
        '[show_sql]': true
>>>>>>> ae25e7826b07dfc0a8f1cc5d79cdb317a3802a3a
  h2:
    console:
      enabled: true
      path: /h2-console

tmdb:
  api:
    key: ${TMDB_API_KEY}
  
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1 hour in milliseconds
