spring:
  application:
    name: backend
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
        show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

tmdb:
  api:
    key: ${TMDB_API_KEY}