spring:
  application:
    name: backend
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: c##idev
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true
        '[show_sql]': true
  h2:
    console:
      enabled: true
      path: /h2-console

tmdb:
  api:
    key: 302b783e860b19b6822ef0a445e7ae53
  
jwt:
  secret: nR8vP6uQx2sLz9F1tYhJkVm3bCeGdHwR
  expiration: 3600000 # 1 hour in milliseconds
  #깃 저장용
openai:
  api: 
    # 이거 파워쉘로 환경변수 따로 넣어줌 윈도우환경변수넣는거 안되더라...
    
