spring:
  application:
    name: backend
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: c##idev
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
        show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
tmdb:
  api:
    key: 302b783e860b19b6822ef0a445e7ae53
server:
  port: 8088